name: dm-test-01
favicon: null
layout_spectrum: 0.97874
typography_spectrum: 0.80905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#2e2b19'
    - '#7a6a52'
    - '#93905b'
  brandStrength: 0.27612965693697333
  lightness: 0.6810306594707072
  saturation: 0.5431751369033009
  rhythmicContrast: 0.48256351985037327
purpose: []
