name: dm-test-01
favicon: null
layout_spectrum: 0.5115961155388504
typography_spectrum: 0.30341021437197924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27612965693697333
  lightness: 0.6810306594707072
  saturation: 0.5431751369033009
  rhythmicContrast: 0.48256351985037327
purpose: []
